POST http://localhost:4000/api/events/
Content-Type: application/json

{
  "title": "ultimo evento",
  "date_start": 11,
  "date_end": 100000000,
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2M2MzMTIxM2FiOTU2YzI4YzdmNTEyNGEiLCJuYW1lIjoic2hlaWxhIiwiaWF0IjoxNjc0MDE1MzU2LCJleHAiOjE2NzQwMjI1NTZ9.OutDd3TPIz4AX_V3HXdk2cnDTqmW-z0viJg1teRs8x8"

}

###
GET http://localhost:4000/api/events
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2M2MzMTIxM2FiOTU2YzI4YzdmNTEyNGEiLCJuYW1lIjoic2hlaWxhIiwiaWF0IjoxNjc0MDk3ODkxLCJleHAiOjE2NzQxMDUwOTF9.xT0yUPlMTgtENP9qcc3sUKOjtMSQcfTPemclOH-JEyY"
}

###

PUT http://localhost:4000/api/events/
Content-Type: application/json

{
  "title": "test evento",
  "date_start": 11,
  "date_end": 100000000,
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2M2MzMTIxM2FiOTU2YzI4YzdmNTEyNGEiLCJuYW1lIjoic2hlaWxhIiwiaWF0IjoxNjc0MDk3ODkxLCJleHAiOjE2NzQxMDUwOTF9.xT0yUPlMTgtENP9qcc3sUKOjtMSQcfTPemclOH-JEyY"
}

###

DELETE http://localhost:4000/api/events/235
Accept: application/json

###
