POST http://localhost:4000/api/events/
Content-Type: application/json

{
  "title": "popopopo",
  "date_start": 11,
  "date_end": 100000000,
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2M2MzMTIxM2FiOTU2YzI4YzdmNTEyNGEiLCJuYW1lIjoic2hlaWxhIiwiaWF0IjoxNjczNzI4NTMyLCJleHAiOjE2NzM3MzU3MzJ9.WPTDzZ0s9id3Vx5DvuHKYw-8SDTCyH9ZV4lHZXaq5QM"

}

###
GET http://localhost:4000/api/events/
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2M2MzMTIxM2FiOTU2YzI4YzdmNTEyNGEiLCJuYW1lIjoic2hlaWxhIiwiaWF0IjoxNjczNzI4NTMyLCJleHAiOjE2NzM3MzU3MzJ9.WPTDzZ0s9id3Vx5DvuHKYw-8SDTCyH9ZV4lHZXaq5QM"
}

###

PUT http://localhost:4000/api/events/235
Accept: application/json

###

DELETE http://localhost:4000/api/events/235
Accept: application/json

###
